print('Hello, Welcome to Python Madlibs')

name = input('Enter your name : ')
n = input('Enter your fav Kpop group :  ')
x = input(f'Enter debut year of {n} : ')
y = input(f'Enter {n} debut album :  ')
r = input(f'Enter {n} Company name :  ')
e = input(f'Enter {n} members number : ')
q = input(f'Enter the anti aging person of {n} :  ')
w = input(f'Enter the Matured person of {n}: ')
t = input(f'Enter the laziest member of {n} :  ')
z = input(f'Enter the Best Dancer of {n}: ')
u = input(f'Enter the shortest member of {n}: ')
v = input(f'Enter the Most Beautiful member of {n} : ')
a = input(f'Enter the more Socialized and young of {n}: ')
b = input(f'Enter the {n} fandom name : ')

print(f'Hello {name} . That was pleasured to hear from you. Here is your madlib')
print(f'{n} is a South Korean band They debuted in {x}. by releasing their Best debut album {y}')
print(f'They came from a company called {r}. They struggled a lot from their debut. Their band has {e} members')
print(f'Where each of them are very talented.')
print(f'{q} is known for best appearance, years may go but not the age ')
print(f'You all know that {w} is the one who thinks and understands better in group')
print(f'{t} is the most laziest member of group')
print(f"{z}'s DANCE is just top notch. A true entertainer of the Group with their expressions")
print(f'{u} is known for cuteness, also have a unique and best voice.')
print(f'{v} is known for untouchable VISUAL and also called as Best when it comes to FASHION & STYLE ')
print(f'{a} is the MAKHNE of the Group. Already very good at everything you could ever imagine.')

print(f'If You are reading until here. Then, No doubt Your one of their biggest {b} in the world')
print(f'Thank You {name} . Your now officially identified as TRUE {b}')
print(f'{b} & {n} forever')
